# Generated by Django 4.2.7 on 2024-06-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DocumentFlow", "0002_alter_file_assigned_to_alter_file_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
