# Generated by Django 4.2.7 on 2024-06-15 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DocumentFlow", "0004_file_rejection_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="rejection_notes",
        ),
    ]
