# Generated by Django 4.2.7 on 2024-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DocumentFlow", "0005_remove_file_rejection_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="rejection_notes",
            field=models.TextField(blank=True),
        ),
    ]
