# Generated by Django 4.2.7 on 2024-06-15 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DocumentFlow", "0007_file_rejectionnote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="rejectionNote",
        ),
    ]
