# Generated by Django 4.2.7 on 2024-06-15 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DocumentFlow", "0008_remove_file_rejectionnote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="rejection_notes",
            new_name="rejection_note",
        ),
    ]
