# Generated by Django 4.2.7 on 2024-06-15 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DocumentFlow", "0009_rename_rejection_notes_file_rejection_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="rejection_note",
            new_name="rejection_notes",
        ),
    ]
